//! Real Verilator recordings generated by ext/surfer/examples/verilator/generate.py.
use std::sync::Arc;
use volna_trace::data::{SignalRef, WaveValue};
use volna_trace::session::OpenSpec;

#[test]
fn raw_bytes_reals_nine_states_and_time_boundaries() {
    let fst = OpenSpec::Bytes {
        name: "wrong-extension.vtr".into(),
        bytes: include_bytes!("../../volna-trace/tests/fixtures/values.fst").to_vec(),
    }
    .open()
    .unwrap();
    assert_eq!(fst.info().timescale, -12);
    assert_eq!(fst.info().time_range, (5, 20));
    let vars: Vec<_> = fst.hierarchy().vars().collect();
    let signals: Vec<_> = vars.iter().map(|v| v.signal).collect();
    let loaded = fst.load_signals(&signals);
    let bytes = loaded[0].1.as_ref().unwrap();
    assert_eq!(bytes.index_at(4), None);
    for result in &loaded[..4] {
        let history = result.1.as_ref().unwrap();
        assert_eq!(history.value(history.index_at(4)), WaveValue::Unavailable);
    }
    assert_eq!(
        bytes.value(bytes.index_at(5)),
        WaveValue::Bytes(vec![b'a', 0, 255, b'\\', b'\n', 128])
    );
    assert_eq!(bytes.value(bytes.index_at(10)), WaveValue::Bytes(vec![]));
    assert_eq!(bytes.value(bytes.index_at(20)), WaveValue::Bytes(vec![]));
    let real = loaded[1].1.as_ref().unwrap();
    assert_eq!(real.value(real.index_at(5)), WaveValue::Real(1.25));
    assert_eq!(real.value(real.index_at(10)), WaveValue::Real(-2.5));
    let logic = loaded[2].1.as_ref().unwrap();
    assert_eq!(
        logic.value(logic.index_at(5)),
        WaveValue::Bits("01xzuwlh-".into())
    );
    assert_eq!(
        logic.value(logic.index_at(9)),
        WaveValue::Bits("01xzuwlh-".into())
    );
    assert_eq!(
        logic.value(logic.index_at(10)),
        WaveValue::Bits("111111111".into())
    );
    assert!(Arc::ptr_eq(logic, loaded[3].1.as_ref().unwrap()));
    assert!(fst.load_signal(SignalRef(u32::MAX)).is_err());
    assert!(fst.load_signals(&[]).is_empty());
    let event = loaded[4].1.as_ref().unwrap();
    assert_eq!(event.shape(), volna_trace::data::SignalShape::Event);
    assert_eq!(
        (0..event.len()).map(|i| event.time(i)).collect::<Vec<_>>(),
        vec![5, 10]
    );
    use volna_core::{
        scene::Scene,
        theme::Theme,
        wave::{paint::paint_event_row, viewport::Viewport},
    };
    let mut scene = Scene::default();
    let area = volna_core::geometry::Rect::from_xywh(0.0, 0.0, 100.0, 24.0);
    paint_event_row(
        event.as_ref(),
        &Viewport {
            start: 0.0,
            end: 20.0,
        },
        area,
        &Theme::one_dark(),
        &mut scene,
    );
    // Arrows of one colour share a primitive: split them at their stems.
    let [
        volna_core::scene::Prim::Lines {
            segments, color, ..
        },
    ] = scene.prims.as_slice()
    else {
        panic!("events are drawn as one set of arrows");
    };
    assert_eq!(*color, Theme::one_dark().wave_signal);
    let stems: Vec<usize> = (0..segments.len())
        .filter(|&k| segments[k][0].x == segments[k][1].x)
        .collect();
    assert_eq!(stems.len(), 2, "one marker per occurrence");
    for (k, (&stem, x)) in stems.iter().zip([25.0, 50.0]).enumerate() {
        let head = &segments[stem + 1..stems.get(k + 1).copied().unwrap_or(segments.len())];
        assert_eq!(segments[stem][0].x, x);
        assert!(segments[stem][0].y < segments[stem][1].y);
        assert!(
            head.iter()
                .all(|[left, right]| { left.x < x && right.x > x && left.y == right.y })
        );
    }
    scene.prims.clear();
    paint_event_row(
        event.as_ref(),
        &Viewport {
            start: 6.0,
            end: 9.0,
        },
        area,
        &Theme::one_dark(),
        &mut scene,
    );
    assert!(scene.prims.is_empty(), "no held event level");

    let file = tempfile::NamedTempFile::new().unwrap();
    let mut writer = vtr::Writer::create(file.path()).unwrap();
    let (_, signal) = writer
        .add_var(
            None,
            "bytes",
            vtr::VarType::String,
            vtr::Direction::Implicit,
            vtr::SignalKind::VarLen,
        )
        .unwrap();
    writer.set_time(5).unwrap();
    writer
        .emit_varlen(signal, &[b'a', 0, 255, b'\\', b'\n', 128])
        .unwrap();
    writer.set_time(10).unwrap();
    writer.emit_varlen(signal, &[]).unwrap();
    writer.close().unwrap();
    let vtr = OpenSpec::Path(file.path().into()).open().unwrap();
    let twin = vtr.load_signal(vtr.hierarchy().var(0).signal).unwrap();
    let signal = vtr.hierarchy().var(0).signal;
    let repeated = vtr.load_signals(&[signal, SignalRef(u32::MAX), signal]);
    assert!(repeated[1].1.is_err());
    assert!(Arc::ptr_eq(
        repeated[0].1.as_ref().unwrap(),
        repeated[2].1.as_ref().unwrap()
    ));
    for time in [5, 9, 10, 20] {
        assert_eq!(
            bytes.value(bytes.index_at(time)),
            twin.value(twin.index_at(time))
        );
    }
}

#[test]
fn vtr_events_preserve_repeated_occurrences_and_render_arrows() {
    use volna_core::{
        geometry::Rect,
        scene::Scene,
        theme::Theme,
        wave::{paint::paint_event_row, viewport::Viewport},
    };
    use volna_trace::data::SignalShape;
    let file = tempfile::NamedTempFile::new().unwrap();
    let mut writer = vtr::Writer::create(file.path()).unwrap();
    let (_, signal) = writer
        .add_var(
            None,
            "event",
            vtr::VarType::Event,
            vtr::Direction::Implicit,
            vtr::SignalKind::Bits {
                width: 1,
                states: 2,
            },
        )
        .unwrap();
    writer
        .add_alias(
            None,
            "event_alias",
            vtr::VarType::Event,
            vtr::Direction::Implicit,
            signal,
        )
        .unwrap();
    for time in [5, 5, 10, 11, 20, 20] {
        writer.set_time(time).unwrap();
        writer.emit_bit(signal, 1).unwrap();
    }
    writer.close().unwrap();
    let session = OpenSpec::Path(file.path().into()).open().unwrap();
    let var = session.hierarchy().var(0);
    assert_eq!(var.shape, SignalShape::Event);
    let alias = session.hierarchy().var(1);
    assert_eq!(alias.shape, SignalShape::Event);
    assert_eq!(alias.signal, var.signal);
    let histories = session.load_signals(&[var.signal, alias.signal]);
    assert!(Arc::ptr_eq(
        histories[0].1.as_ref().unwrap(),
        histories[1].1.as_ref().unwrap()
    ));
    let history = session.load_signal(var.signal).unwrap();
    assert_eq!(history.shape(), SignalShape::Event);
    assert_eq!(
        (0..history.len())
            .map(|i| history.time(i))
            .collect::<Vec<_>>(),
        [5, 5, 10, 11, 20, 20]
    );
    let theme = Theme::one_dark();
    let single = theme.wave_signal;
    let multiple = theme.wave_event_coalesced;
    assert_ne!(single, multiple);
    for (start, end, width, colors) in [
        (0.0, 20.0, 100.0, vec![multiple, single, single, multiple]),
        (5.0, 10.0, 100.0, vec![multiple, single]),
        (5.1, 9.9, 100.0, vec![]),
        (0.0, 100.0, 2.0, vec![multiple]),
        (10.0, 11.0, 100.0, vec![single, single]),
        (10.0, 100.0, 2.0, vec![multiple]),
        // A neighbouring event outside the viewport must not affect colour.
        (10.0, 10.5, 0.1, vec![single]),
        (20.0, 21.0, 100.0, vec![multiple]),
    ] {
        let mut scene = Scene::default();
        paint_event_row(
            history.as_ref(),
            &Viewport { start, end },
            Rect::from_xywh(30.0, 10.0, width, 24.0),
            &theme,
            &mut scene,
        );
        // Each arrow's colour, left to right, from its stem.
        let mut stems: Vec<(f32, volna_core::Color)> = scene
            .prims
            .iter()
            .flat_map(|prim| {
                let volna_core::scene::Prim::Lines {
                    segments, color, ..
                } = prim
                else {
                    panic!("expected event arrows");
                };
                segments
                    .iter()
                    .filter(|[a, b]| a.x == b.x)
                    .map(move |[a, _]| (a.x, *color))
            })
            .collect();
        stems.sort_by(|a, b| a.0.total_cmp(&b.0));
        let actual: Vec<_> = stems.into_iter().map(|(_, color)| color).collect();
        assert_eq!(actual, colors, "viewport {start}..{end} width {width}");
    }
}
