//! Real Verilator recordings generated by ext/surfer/examples/verilator/generate.py.
use std::path::PathBuf;
use std::sync::Arc;
use volna_core::data::{SignalRef, WaveValue};
use volna_core::session::OpenSpec;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../ext/surfer/examples/verilator")
        .join(name)
}

#[test]
fn equivalent_verilator_traces_agree_at_every_change() {
    for design in ["features", "operators", "pipeline"] {
        let fst = OpenSpec::Path(fixture(&format!("{design}.fst")))
            .open()
            .unwrap();
        let vtr = OpenSpec::Path(fixture(&format!("{design}.vtr")))
            .open()
            .unwrap();
        assert_eq!(fst.info().timescale, vtr.info().timescale);
        let signals: Vec<_> = fst.hierarchy().vars.iter().map(|v| v.signal).collect();
        let histories = fst.load_signals(&signals);
        for (id, variable) in fst.hierarchy().vars.iter().enumerate() {
            let name = fst.hierarchy().full_name(id);
            let other = vtr
                .hierarchy()
                .vars
                .iter()
                .enumerate()
                .find(|(i, _)| vtr.hierarchy().full_name(*i) == name)
                .unwrap_or_else(|| panic!("missing {name}"));
            assert_eq!(variable.shape, other.1.shape);
            let a = histories[id].1.as_ref().unwrap();
            let b = vtr.load_signal(other.1.signal).unwrap();
            let times = (0..a.len())
                .map(|i| a.time(i))
                .chain((0..b.len()).map(|i| b.time(i)));
            for time in times {
                let left = a.value(a.index_at(time));
                let right = b.value(b.index_at(time));
                if matches!((&left, &right), (WaveValue::Real(a), WaveValue::Real(b)) if a.is_nan() && b.is_nan())
                {
                    continue;
                }
                assert_eq!(left, right, "{design}: {name} at {time}");
            }
        }
    }
}

#[test]
fn malformed_images_report_errors() {
    for bytes in [vec![], b"not a trace".to_vec(), vec![0; 9]] {
        assert!(
            OpenSpec::Bytes {
                name: "trace.fst".into(),
                bytes
            }
            .open()
            .is_err()
        );
    }
}

#[test]
fn truncated_sections_and_overflowing_lengths_return_errors() {
    let original = include_bytes!("fixtures/values.fst");
    // Selected truncated prefixes must fail cleanly.
    for end in [9, 100, 329, original.len() - 1] {
        assert!(
            OpenSpec::Bytes {
                name: "truncated.fst".into(),
                bytes: original[..end].to_vec()
            }
            .open()
            .is_err(),
            "prefix {end}"
        );
    }
    for size in [0u64, 7, u64::MAX] {
        let mut bytes = original.to_vec();
        let offset = 330; // first section after the fixed FST header
        bytes[offset + 1..offset + 9].copy_from_slice(&size.to_be_bytes());
        assert!(
            OpenSpec::Bytes {
                name: "bad-length.fst".into(),
                bytes
            }
            .open()
            .is_err()
        );
    }
}

#[test]
fn gzip_wrapper_preserves_values_and_rejects_truncation() {
    let wrapped = include_bytes!("fixtures/values-wrapped.fst");
    assert_eq!(wrapped[0], 254);
    let open = |bytes: Vec<u8>| {
        OpenSpec::Bytes {
            name: "wrapped.fst".into(),
            bytes,
        }
        .open()
    };
    let a = open(wrapped.to_vec()).unwrap();
    let b = open(include_bytes!("fixtures/values.fst").to_vec()).unwrap();
    assert_eq!(a.info().time_range, b.info().time_range);
    for id in 0..4 {
        let a = a.load_signal(a.hierarchy().vars[id].signal).unwrap();
        let b = b.load_signal(b.hierarchy().vars[id].signal).unwrap();
        assert_eq!(a.len(), b.len());
        for i in 0..a.len() {
            assert_eq!(a.time(i), b.time(i));
            assert_eq!(a.value(Some(i)), b.value(Some(i)));
        }
    }
    assert!(open(wrapped[..wrapped.len() - 1].to_vec()).is_err());
}

#[test]
fn unsupported_time_and_dump_metadata_is_explicit_even_when_wrapped() {
    use std::io::Write;
    let original = include_bytes!("fixtures/values.fst");
    let mut shifted = original.to_vec();
    shifted[322..330].copy_from_slice(&(-10i64).to_be_bytes());
    let mut blackout = original.to_vec();
    blackout.push(2);
    blackout.extend_from_slice(&13u64.to_be_bytes());
    blackout.extend_from_slice(&[2, 0, 10, 1, 5]);
    for (bytes, expected) in [(shifted, "time offsets"), (blackout, "dump-off")] {
        let mut encoder = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
        encoder.write_all(&bytes).unwrap();
        let compressed = encoder.finish().unwrap();
        let mut wrapped = vec![254];
        wrapped.extend_from_slice(&(compressed.len() as u64 + 16).to_be_bytes());
        wrapped.extend_from_slice(&(bytes.len() as u64).to_be_bytes());
        wrapped.extend_from_slice(&compressed);
        for image in [bytes, wrapped] {
            let error = OpenSpec::Bytes {
                name: "metadata.fst".into(),
                bytes: image,
            }
            .open()
            .err()
            .expect("unsupported metadata");
            assert!(error.to_string().contains(expected), "{error:#}");
        }
    }
}

#[test]
fn raw_bytes_reals_nine_states_and_time_boundaries() {
    let fst = OpenSpec::Bytes {
        name: "wrong-extension.vtr".into(),
        bytes: include_bytes!("fixtures/values.fst").to_vec(),
    }
    .open()
    .unwrap();
    assert_eq!(fst.info().timescale, -12);
    assert_eq!(fst.info().time_range, (5, 20));
    let vars = &fst.hierarchy().vars;
    let signals: Vec<_> = vars.iter().map(|v| v.signal).collect();
    let loaded = fst.load_signals(&signals);
    let bytes = loaded[0].1.as_ref().unwrap();
    assert_eq!(bytes.index_at(4), None);
    for result in &loaded[..4] {
        let history = result.1.as_ref().unwrap();
        assert_eq!(history.value(history.index_at(4)), WaveValue::Unavailable);
    }
    assert_eq!(
        bytes.value(bytes.index_at(5)),
        WaveValue::Bytes(vec![b'a', 0, 255, b'\\', b'\n', 128])
    );
    assert_eq!(bytes.value(bytes.index_at(10)), WaveValue::Bytes(vec![]));
    assert_eq!(bytes.value(bytes.index_at(20)), WaveValue::Bytes(vec![]));
    let real = loaded[1].1.as_ref().unwrap();
    assert_eq!(real.value(real.index_at(5)), WaveValue::Real(1.25));
    assert_eq!(real.value(real.index_at(10)), WaveValue::Real(-2.5));
    let logic = loaded[2].1.as_ref().unwrap();
    assert_eq!(
        logic.value(logic.index_at(5)),
        WaveValue::Bits("01xzuwlh-".into())
    );
    assert_eq!(
        logic.value(logic.index_at(9)),
        WaveValue::Bits("01xzuwlh-".into())
    );
    assert_eq!(
        logic.value(logic.index_at(10)),
        WaveValue::Bits("111111111".into())
    );
    assert!(Arc::ptr_eq(logic, loaded[3].1.as_ref().unwrap()));
    assert!(fst.load_signal(SignalRef(u32::MAX)).is_err());
    assert!(fst.load_signals(&[]).is_empty());
    assert!(
        loaded[4]
            .1
            .as_ref()
            .err()
            .unwrap()
            .to_string()
            .contains("event occurrences")
    );

    let file = tempfile::NamedTempFile::new().unwrap();
    let mut writer = vtr::Writer::create(file.path()).unwrap();
    let (_, signal) = writer.add_var(
        "bytes",
        vtr::VarType::String,
        vtr::Direction::Implicit,
        vtr::SignalKind::VarLen,
    );
    writer.set_time(5).unwrap();
    writer
        .emit_varlen(signal, &[b'a', 0, 255, b'\\', b'\n', 128])
        .unwrap();
    writer.set_time(10).unwrap();
    writer.emit_varlen(signal, &[]).unwrap();
    writer.close().unwrap();
    let vtr = OpenSpec::Path(file.path().into()).open().unwrap();
    let twin = vtr.load_signal(vtr.hierarchy().vars[0].signal).unwrap();
    let signal = vtr.hierarchy().vars[0].signal;
    let repeated = vtr.load_signals(&[signal, SignalRef(u32::MAX), signal]);
    assert!(repeated[1].1.is_err());
    assert!(Arc::ptr_eq(
        repeated[0].1.as_ref().unwrap(),
        repeated[2].1.as_ref().unwrap()
    ));
    for time in [5, 9, 10, 20] {
        assert_eq!(
            bytes.value(bytes.index_at(time)),
            twin.value(twin.index_at(time))
        );
    }
}
